### PR TITLE
[Feature #36] Add new APIs for benchmarks of Flux nodes, calculate the percentages and show up

### LINKED ISSUE #36: Flux Network Utilisation
### Problem Description

Like to visually show Utilisation across the Flux network at the given point of time at a refresh. Similar to the data today that counts Total nodes, price, and the count per node tier. Similar today no history is needed and as much as possible trying to stay away from any DB's.

### Tracking Metrics

Looking to track 4 metrics

1. Node Utilisation: % metric. This is the total: (Total nodes - Nodes with 0 apps)/Total nodes %
2. CPU Utilisation: % metric. (Total benchmark Threads - Total locked cores)/Total Threads
3. Ram Utilisation : % metric. (Total bench marked Ram - Total locked ram)/ Total bench marked ram
4. SSD Utilisation: % metric. (Total benchmark SSD - Total locked ram)/Total benchmark SSD

### UI & Design Ideas

Looking to make it as visual and fun as possible sticking to the sites existing design. But besides just showing numbers like to make use of visual effects, idea so far is speedo dials or numbers within a circle. At this stage circle is what i had in mind. Colour full is ideal.

- Some ideas around imaging: https://youtu.be/MOHRbw1TZgA
-  Idea is that these numbers would have a roll effect but very quickly settle to where they should be based on the number as its % based it should roll up quickly. Nothing longer than 5 seconds.

image
image

- **Location**: Not exactly sure where on the screen makes the most sense to place it, gut feel is towards the top if possible 
- **Crazy idea**: Potentially within the existing blocks where we have data today:

image

Happy to have a look to what makes most sense. Also one of the guys mentioned seeing we using React may be look at [Framer for React](https://www.framer.com/motion/)

### Technical Data

**Total Resource**

This should be fairly easy to calculate in two ways:

1. Either count the total nodes per tier, and then multiply with the Resource specifications per tier. Suspect this will be good from performance perspective.

2. Stats.runonflux.io: Should be able to count the specifications benchmarked as that will have the true resources. This might take a little longer to calculate but should be what we use. more discussed in API section.

**Resource Utilisation** 

This should be easy with the Stats.runonflux.io and have a look at the locked resources. Example code in the API section.

**API**
If we have more efficient ways by all means but looking at what we already using today. Some ideas around calculating Resource utilisation:

- `https://stats.runonflux.io/fluxinfo/apps.resources`

image

Couple things we need to be careful for:

- Cores: This is actually vCores (Threads) so we will have to calculate usage with threads in mind
- Ram: The above mentioned API will show Ram in MB, this will probably be better displayed on site in TB

_Node Utilisation_ 

This calculation we need to make use of our existing code to count the apps. But in this case we just need to make sure we can the 0 app nodes:

image

Also these nodes will return no locked resources like this:

image

### Pseudo Code Examples

Couple example of code to calculate the values we need.

**_Node Resource Utilisation_**

- Locked up Ram:

```
const api_url = 'https://stats.runonflux.io/fluxinfo/apps.resources'
  async function getdata() {
    const res = await fetch(api_url);
    const json = await res.json();  
    var sumram  = 0;  
    json.data.map((index)=> { sumram = sumram + (index?.apps?.resources?.appsRamLocked)});
    console.log(sumram/1000000,"Tb");
  }
getdata();
```

image

**_Total Resources_**

Using the same API, but focusing on Ram. In this case the API returns ram in GB and not MB above:

```
const api_url = 'https://stats.runonflux.io/fluxinfo/benchmark'
  async function getdata() {
    const res = await fetch(api_url);
    const json = await res.json();  
    var sumram  = 0;  
    json.data.map((index)=> { sumram = sumram + (index?.benchmark?.bench?.ram)});
    console.log(sumram/1000,"Tb");
  }
getdata();
```
image

**_Node Utilization_**

To calculate this we can use existing data. Today in the main screen we count total nodes, thus we have the base value to devide to calculate % utilisation, thus calculation will be:  Node Utilisation = Utilised nodes/Total nodes  

To calculate Utilised nodes:

```
const api_url = 'https://stats.runonflux.io/fluxinfo/apps.resources'
  async function getdata() {
    const res = await fetch(api_url);
    const json = await res.json();  
    const sumemptynodes = json.data.filter((data) => data.apps.resources.appsRamLocked == 0).length;
    console.log(sumemptynodes);
  }
getdata();
```

image

### PR DESCRIPTION
**Pull request by Hiroshi97**
Resolve #36
- Add new APIs for Flux nodes' benchmarks
- Calculate & display the percentages

### CODE REVIEW

**Comment by 2ndtlmining** [comment]
@Hiroshi97 This is amazing! Love the colours. 

image

Couple small things, not sure if you want me to merge as is or wait a bit but what i spotted if it is possible to change:

- Any chance we could detach the loading of the stats with the normal loading of the data like Node counts, prices ect. I understand that the Network stats will take a bit longer to load as it needs to get data from that stats api that takes long. If we could do it in 2 steps?
- Calcs update. Think the calcs is calculating not utilised usage which is ok, but if we can change that to utilized, thus = Locked resources / Total benched resources

image

- Any chance we can add a tooltip on the boxes to show
  - Utilised 
  - Total

Thus if we look at the node utilization as example, which is about 40%, should be like

- 6000 Utilised
- 15000 Available 

something to that tune?

**Comment by Hiroshi97** [comment]
@2ndtlmining Hi, I've updated the code. Please check and let I know if I'm still missing anything. Thanks!

**Comment by 2ndtlmining** [comment]
@Hiroshi97 Thanks again, starting to look great. Just a couple things, but again i apologies i am explaining like my backside :)

1. Node utilisation. Think we got it the wrong way around:
image

What i am thinking is this more or less (not sexy at all and my bad attempt):

image

> const api_url = 'https://stats.runonflux.io/fluxinfo/apps.resources'
>   async function getdata() {
>     const totalnodes = 15292; // we get this from our original API to count total nodes
>     const res = await fetch(api_url);
>     const json = await res.json();  
>     const sumemptynodes = json.data.filter((data) => data.apps.resources.appsRamLocked == 0).length;
>     console.log("Emptynodes= "+ sumemptynodes);
>     const utilized = ((totalnodes - sumemptynodes)/totalnodes) * 100;
>     console.log("Node Utilization= "+ utilized + " %");
>   }
> getdata();
> 

2. CPU, Ram and SSD not calculating for some reason:

image

What i was thinking is something like this for Ram, but for all 3 just with the different API data element (again not sexy):

image

> const api_urlutil = 'https://stats.runonflux.io/fluxinfo/apps.resources'
>   async function getdatautilised() {
>     const res = await fetch(api_urlutil);
>     const json = await res.json();  
>     var sumram  = 0;  
>     json.data.map((index)=> { sumram = sumram + (index?.apps?.resources?.appsRamLocked)});
>     console.log("Utilized Ram = "+ sumram/1000000," Tb");
>   }
> 
>   const api_url = 'https://stats.runonflux.io/fluxinfo/benchmark'
>   async function gettotaldata() {
>     const res = await fetch(api_url);
>     const json = await res.json();  
>     var sumram  = 0;  
>     json.data.map((index)=> { sumram = sumram + (index?.benchmark?.bench?.ram)});
>     console.log("Total Ram = " + sumram/1000,"Tb");
>   }
> 
> getdatautilised();
> gettotaldata();
> //Percentage is just these two devided Utilized / Total


3. Data loading: Noticed that nothing is loading at all until a wallet is put in. Was wondering if we can still do it as part of the Gstore load or the main set, but just load the data as it comes available. Almost similar to what we have done with the Node Overview, data loads in as its available. What happens now is nothing loads until everything is in. But not sure what is possible. But if not possible totally undertstand.
4. Tooltips: You are the man thank you soo much! Wondering if we can add the naming at the back, like "vCores", "TB", "TB"


Sorry hopefully i am not too much of a pain

**Comment by 2ndtlmining** [comment]
Hey @Hiroshi97 

Thanks a lot. Really really apologies. Think i am confusing you. Your 100% spot on. Should use the correct dataset for the data :)
Thus Cores for cores, Ram for Ram and SSD for SSD. I just used the Ram as an example to extract the data. Sorry didnt meen we need to take the Ram for the SSD also :)

Looking at the changes you made its fantastic.

image

- Node Utilization perfect
- vCores is perfect
- Ram is perfect
- SSD part is where i have confused you i am really sorry (you prob already know what to do )

For SSD we should be using something like this:

image

Looking at the actual API data we getting back from Benchmark and Locked resources looks to be setup in Gb's, so at least its the same. Also i know it says Hdd, but i am 100% sure its SSD requirement.  my crappy code:

`const api_urlutil = 'https://stats.runonflux.io/fluxinfo/apps.resources'
  async function getdatautilised() {
    const res = await fetch(api_urlutil);
    const json = await res.json();  
    var sumssd  = 0;  
    json.data.map((index)=> { sumssd= sumssd + (index?.apps?.resources?.appsHddLocked)});
    console.log("Utilized SSD = "+ sumssd/1000," Tb"); // This data looks to be in Gb
  }

  const api_url = 'https://stats.runonflux.io/fluxinfo/benchmark'
  async function gettotaldata() {
    const res = await fetch(api_url);
    const json = await res.json();  
    var sumtssd  = 0;  
    json.data.map((index)=> { sumtssd = sumtssd + (index?.benchmark?.bench?.ssd)});
    console.log("Total SSD = " + sumtssd/1000,"Tb"); //This api data looks to be in Gb
  }

getdatautilised();
gettotaldata();
//Percentage is just these two devided Utilized / Total
`

**Comment by 2ndtlmining** [comment]
Btw i did log a ticket with the team. The Stats API very inconsistent for me. Would think same for you

image

I get the same response every now and again on the benchmarks: 

https://stats.runonflux.io/fluxinfo/benchmark

Not sure what is best way to deal with it if it comes. My thinking was just to put 0 or something like NAN or NA = Not available.
Thinking longer term may be better to do our internal DB to hit the api and update our table every 30min, think that will increase performance a lot also. But thats for future.

**Comment by Hiroshi97** [comment]
@2ndtlmining
You're right, the Utilization stats are fetched again when the wallet address is input. The default stats are re-fetched as well but they don't have any transitions so they look like stay the same meanwhile the circular ones have transitions. I've temporarily fixed the re-fetch btw.

About the API issue, yeah thought it was my internet :). I'm going to use both 0 and NA for it

**Comment by 2ndtlmining** [comment]
@Hiroshi97 Man this is fantastic!! Absolutely love it. Looks soo cool:

image

Spotted the SSD utilization, it taking the ram, but thats a small thing, think i can fix that myself also.

Thanks soo much!

**Comment by 2ndtlmining** [comment]
@Hiroshi97 Managed to update the SSD no issue, but noticed, that if we have some data not available in the Utilisation part (thats coming from stats API) it doesnt load any wallet information if a person searches. Almost like it blocks searching. Do you recon there is a way to decouple that?

**Pull request merged**
