### PR TITLE
Feature: Gamification (Best Uptime and Most hosted app)

### PR DESCRIPTION
**Pull request by Hiroshi97**

### CODE REVIEW

**Comment by victorquanlam** [comment]
Possible performance in the future for the loading time: 

- Initially we can an API endpoint to get all raw nodes but doesn't have extra info such as uptime, app counts
- After that we call additional API to get these info, so that makes the Best Uptime and Most hosted app to wait for all of them to be fulfilled in order to display
=> if the initial API call provides all the required data then we don't need to call and fetch the other info like app count and uptime. This will improve the loading time by miles.

**Comment by 2ndtlmining** [comment]
I really like what have been done, the colours and information looks great!
Best uptime is perfect thank you soo much.

2 minor things if you could have a look please:

1. Home page loading: Suspect this is similar to the Demo page issue, but the Payout timer, Best Uptime and Most hosted app is loading even without putting in address:

image

If we could not render them if possible during the home page, but only once we search.

2. Section name: Suspect the logic you applied is not exactly what i was looking for, but its not a train smash. Think the way logic is working is its picking up the node that has the most hosted apps on for example:
image

And not really counting the app that is the most hosted :) But again not a train smash. Lets keep it to make changes to a minimum and then go after the most hosted app next time. Hope to be once this order is done if you are interested.

But could we please change the name of the section to " Most Hosted Node" please

**Comment by Hiroshi97** [comment]
@2ndtlmining Hi,
Thanks for the detailed feedback. Just to clarify the second one: Does it mean we are going to search for the app with the most instances among all nodes or just the app of the node which has the highest app count?

For example:
Node 1 - 3 Apps [100 instances, 48 instances, 3 instances]
Node 2 - 2 Apps [105 instances, 89 instances]
Node 3 - 1 App [99 instances]

So we are going to pick the Node 1 because it has most apps, then going to pick the most hosted app (100 instances) or we are going to pick 105 instances immediately because it is the highest one among all nodes?

**Comment by 2ndtlmining** [comment]
Love the questions. Short answer is Yes, we will pick up Node 1. 

Long answer, there should not be duplicate instances of an app on 1 single node, as generally they will be deployed with a specific port in mind. So even the busy node will only have 1 of the specific app. Or at least thats my understanding :)

**Comment by Hiroshi97** [comment]
@2ndtlmining Yes, each app has its own instance, I'm just confused with what are shown here for the number of instances: 
image

So I reckon it is similar to a total number the app has been hosted, since we don't have any other data which illustrate that. 

Btw, I've pushed an update, feel free to give a feedback after testing it. Thank you!

**Comment by 2ndtlmining** [comment]
Hey mate

Hehe yeah think i confused you. Had a look and see its now a little messy :)
On the great side, loading is perfect now. Dont have that loading screen so thats perfect.

image

Could i please ask if we go back to the on the previous way you calculated Most hosted app, but just change the name to "Most Hosted Node". I felt that in that screenshot i posted it was calculating correctly or at least the checks i checked on couple  wallets.

Now for your question: The screenshot you showing there is actual the customer side. So a person can pay for an app, and that app will then be hosted on nodes. So what you looking at, is 1 customer bought 60 instances of Presearch.

The angle of the website and app is more from the Node provider. Thus the person hosting these apps for the Customer. So what i want to show the Node provider is which is his busiest node (which i think was working correctly before) and then also out of his nodes what app was the most hosted. But the most hosted app, we can do that in next update. Thus to not stuff you around too much, we can just change the name and keep your 1st calcs that would be perfect

**Comment by Hiroshi97** [comment]
@2ndtlmining Thanks for your detailed explanation. I've reverted the changes.

**Comment by 2ndtlmining** [comment]
Great stuff! Love it thanks you soo much

**Pull request merged**
