### PR TITLE
[Update] Update Fractus vitals - Resolve #24

### LINKED ISSUE #24: Fractus Rewards update
Fractus rewards has finally been announced and lined out in Medium article:

https://fluxofficial.medium.com/earn-more-with-fractus-cumulus-store-more-flux-earned-cbeac46bc9e7

Reading through the details couple things confirmed:

- Part of the Cumulus queue: Thus reward times will be based on the queues for Cumulus thus timing should be that.
- Collateral: 1000 exactly same as Cumulus
- Rewards: 15% bonus ontop of the current Cumulus native flux reward. This is key determination as Fractus will not get any PA, so care needs to be taken with APR , and PA calculations

**Front-end changes**

_Header_
image

- Frequency
- Rewards
- APR
- Total node count: As far as i understand API still doesnt have data, but might code in as i have requested it

image

The expectation is that there will not be fractus there as such we need to use another api and code as specified here:

image

Just getting a Promise issue, when doing into the website. I struggling to get the await and promise to work on the website as needed. Hopefully someone can help.

_Estimated Earnings_

image

- $ amount in Day and Month to be updated to include Fractus
- Flux amount in Day and month to be updated to include Fractus 

**Back-end changes**

As Fractus really is part of Cumulus need to perform some updates in couple places but majority i expect:

- apidata.js: Need to add Fractus in there, eventhough there is going to eventually be a node count, that should not be used as the queue lenght as the queue lenght will be based on Cumulus. Thus reward calcs should use Cumulus, but display Zelcount data in front end
- app-content.js: Need to update the rewards. But this is where it gets interesting as Fractus will only get 15% bump on Native flux, no Parallel asset rewards thus those values should not be taken into account.
- API: https://stats.runonflux.io/fluxinfo?projection=benchmark.bench.thunder,benchmark.bench.ipaddress - 
image

**Testing key points**

- Tooltip needs to have a bump in the Flux per day but not the PA's (as 15% is only native flux)
- Double/tripple check the estimated earnings as it will be a different type of calculation

### PR DESCRIPTION
**Pull request by Hiroshi97**
Resolve #24

### CODE REVIEW

**Comment by Hiroshi97** [comment]
@2ndtlmining I've updated the calcs, please let us know whether it's correct or not. Thank you!

**Comment by 2ndtlmining** [comment]
Thanks a lot for the quick response and help with the synch/wait functions. Very much appreciated.
Apologies might not have clearly explained the calcs, but its slightly wrong. Below is visually:

image

- Pay Frequency: Works Perfectly thanks.
- Flux per day: not sure how the 0.853 is exactly calculated but what it should be is something like:

: (0.371 * 1.15) + (normal PA which 0.260 as there is no bonus PA purely on Native Flux)
- APR: Not entirely correct, would be great project to invest in :). But it should be the total of the Flux per day values over 365 similar to all the other cals. And because its really only 15% native asset bump we really looking at like max 25% is my rough calculation

**Comment by Hiroshi97** [comment]
Since we are not proficient in Flux and its calc so I'm not sure if this fix is still correct. You can take a look at `File changes` to see as we are only change the calcs

**Comment by 2ndtlmining** [comment]
@Hiroshi97 Hopefully by the end you running your own Flux node :)
Btw should look into hosting apps on it, its fairly cheap :)

**Comment by 2ndtlmining** [comment]
@Hiroshi97 perfect thank you very very much! Not only with the calcs and update but also sharing how to deal with the sync/wait effectively. 

image

**Pull request merged**
