### PR TITLE
Feature: Parallel Assets - Algorand

### PR DESCRIPTION
**Pull request by Hiroshi97**
- Add `Algorand` to Parallel Assets

### CODE REVIEW

**Review by 2ndtlmining — APPROVED** [review]

**Comment by 2ndtlmining** [comment]
The Algo changes are great. Got some conflicts, so just merged the algo changes

**Comment by Hiroshi97** [comment]
@2ndtlmining It's ready to be merged now. The conflict is solved!

**Comment by 2ndtlmining** [comment]
Thanks you soo much!

**Comment by 2ndtlmining** [comment]
Hey Team Could you please delete the pull request against anh-dinh-jh please

**Pull request merged**
